### PR TITLE
Fix missing components in ellipticarc description

### PR DESCRIPTION
**Pull request by nyalldawson**
And make the different descriptions consistent with each other

### CODE REVIEW

**Comment by williamscraigm** [comment]
Fixed as part of https://github.com/Esri/cim-spec/commit/cb362921154f0143f6ec9c2119c71b091540143d - formatting was a bit different than in your example and there was another escaping issue. Thanks @nyalldawson

**Comment by nyalldawson** [comment]
Thanks @williamscraigm ! I've also seen some occurances of elliptical arcs with only 4 elements in the list which are not covered by the documentation, e.g.:

```
[[
   [0.0, 5.0],
   {'a': [[0.0, 5.0], [0.0, 0.0], 0, 1]},
   [0.0, 5.0]
]]
```

It seems like these might be used for circles, with the first two elements as the end point and center point (and maybe the 4th element is the "is clockwise" flag?).

**Comment by williamscraigm** [comment]
I'm thinking that's covered by the REST documentation here which documents an older format prior to 10.3? https://developers.arcgis.com/documentation/common-data-types/geometry-objects.htm

**Comment by nyalldawson** [comment]
@williamscraigm right -- that matches my findings then! Do you think it's worth documenting here too, given that it appears in some symbol definitions?

**Comment by williamscraigm** [comment]
Do you have an example of where you're seeing this because I don't believe the modern versions of apps should be producing it?

**Comment by nyalldawson** [comment]
@williamscraigm The "Line with 1 marker" symbol from the ArcGIS 2D style has it, for example:

```
{
  "type": "CIMLineSymbol",
  "symbolLayers": [
    {
      "type": "CIMVectorMarker",
      "enable": true,
      "anchorPoint": {
        "x": 0,
        "y": 0
      },
      "anchorPointUnits": "Relative",
      "dominantSizeAxis3D": "Y",
      "size": 4,
      "billboardMode3D": "FaceNearPlane",
      "markerPlacement": {
        "type": "CIMMarkerPlacementAlongLineSameSize",
        "placePerPart": true,
        "angleToLine": true,
        "controlPointPlacement": "NoConstraint",
        "endings": "Custom",
        "offsetAlongLine": 15,
        "placementTemplate": [
          30
        ]
      },
      "frame": {
        "xmin": -5.0,
        "ymin": -5.0,
        "xmax": 5.0,
        "ymax": 5.0
      },
      "markerGraphics": [
        {
          "type": "CIMMarkerGraphic",
          "geometry": {
            "curveRings": [
              [
                [
                  0.0,
                  5.0
                ],
                {
                  "a": [
                    [
                      0.0,
                      5.0
                    ],
                    [
                      0.0,
                      0.0
                    ],
                    0,
                    1
                  ]
                },
                [
                  0.0,
                  5.0
                ]
              ]
            ]
          },
          "symbol": {
            "type": "CIMPolygonSymbol",
            "symbolLayers": [
              {
                "type": "CIMSolidFill",
                "enable": true,
                "color": {
                  "type": "CIMRGBColor",
                  "values": [
                    0,
                    0,
                    0,
                    100
                  ]
                }
              }
            ]
          }
        }
      ],
      "scaleSymbolsProportionally": true,
      "respectFrame": true
    },
    {
      "type": "CIMSolidStroke",
      "effects": [
        {
          "type": "CIMGeometricEffectDashes",
          "dashTemplate": [
            20,
            10
          ],
          "lineDashEnding": "HalfPattern",
          "controlPointEnding": "NoConstraint"
        },
        {
          "type": "CIMGeometricEffectOffset",
          "method": "Bevelled",
          "offset": 0,
          "option": "Fast"
        }
      ],
      "enable": true,
      "capStyle": "Round",
      "joinStyle": "Round",
      "lineStyle3D": "Strip",
      "miterLimit": 10,
      "width": 1,
      "color": {
        "type": "CIMRGBColor",
        "values": [
          0,
          0,
          0,
          100
        ]
      }
    }
  ]
}
```

**Comment by williamscraigm** [comment]
Got it, I see how that's still used in some cases. Doc has been updated.

**Comment by nyalldawson** [comment]
Thanks @williamscraigm !

**Pull request closed without merging**
